### ISSUE TITLE
Kovan config addresses are not correct

### ISSUE THREAD

**Issue by nickoneill** [outprog/gozx#1]
The proper ones are listed here:

https://0x.org/wiki#Deployed-Addresses

**Comment by outprog** [comment]
@nickoneill 
Addresses are correct. Old version used beta addresses.

https://github.com/outprog/gozx/blob/master/models/config.go#L29-L31

ERC20Proxy: 0xf1ec01d6236d3cd881a0bf0130ea25fe4234003e
ERC721Proxy: 0x2a9127c745688a165106c11cd4d647d2220af821
Exchange: 0x35dd2932454449b14cee11a94d3674a936d5d7b2

**Comment by nickoneill** [comment]
Oh thanks! I guess I was pinned to an earlier version
